# Generated by Django 5.1.2 on 2024-10-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('user_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('profile_image', models.CharField(blank=True, default=None, max_length=120, null=True)),
            ],
            options={
                'db_table': 'user_tb',
            },
        ),
    ]
