# Generated by Django 5.1.2 on 2024-10-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_data', '0002_alter_user_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
